use crate::ui::page_macros::gallery_static_page;
use makepad_components::makepad_widgets::*;

gallery_static_page! {
    widget: GalleryIconGalleryPage,
    page: icon_gallery_page,
    title: "Icons",
    subtitle: "Generated Lucide icon components from makepad-icon/resources/icons.",
    divider: { ShadHr{} },
    preview_spacing: 12.0,
    preview: {
        // Generated by makepad-gallery/build.rs (GENERATED_PREVIEW_FILENAME).
        include!(concat!(env!("OUT_DIR"), "/icon_preview_rows.rs"));
    },
    action_flow: {
        mod.widgets.GalleryActionFlowStep{text: "1. Run `python3 makepad-icon/scripts/download_lucide_icons.py --clean` to refresh SVG assets from Lucide."}
        mod.widgets.GalleryActionFlowStep{text: "2. Build `makepad-icon` or `makepad-gallery`; build.rs scans icons and generates icon components automatically."}
        mod.widgets.GalleryActionFlowStep{text: "3. Open this page to visually spot-check icon rendering and names before using them in components."}
    },
}
